import { Inter } from "next/font/google";
import "../Styles/globals.css";
import { BrowserRouter } from "react-router-dom";
import Navbar from "@Components/Navbar";
import Footer from "@Components/Fotter";
import { ThemeProvider } from "@context/ThemeContext";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <Navbar />
          <Suspense >
            {children}
          </Suspense>
          <Footer />
        </ThemeProvider>
      </body>
    </html >
  );
}
